import { FileBarChart } from "lucide-react";
import { AgencyComingSoon } from "@/features/agency/components/coming-soon";

export default function AgencyReportsPage() {
  return (
    <AgencyComingSoon
      title="Reports"
      description="One-click daily, weekly, and monthly reports, generated by AI Coach."
      icon={FileBarChart}
      phase="Phase 3"
    />
  );
}
